### ISSUE TITLE
Uncaught TypeError: Cannot read property 'screenPositionForBufferPosition' of undefined

### ISSUE THREAD

**Issue by Ad115** [JoelBesada/activate-power-mode#153] opened 2016-05-20 07:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'screenPositionForBufferPosition' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'screenPositionForBufferPosition' of undefined
    at Object.module.exports.ActivatePowerMode.spawnParticles (/home/agarcia_pc/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:99:29)
    at Object.debounced [as throttledSpawnParticles] (/home/agarcia_pc/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/home/agarcia_pc/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:75:8)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:12)
    at SearchCallbackArgument.replace (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:75:26)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:3:59
    at /usr/share/atom/resources/app.asar/node_modules/whitespace/lib/whitespace.js:138:18
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:921:18
    at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:949:9)
    at TextBuffer.module.exports.TextBuffer.backwardsScanInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:960:19)
    at TextBuffer.module.exports.TextBuffer.backwardsScan (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:917:19)
    at Whitespace.module.exports.Whitespace.removeTrailingWhitespace (/usr/share/atom/resources/app.asar/node_modules/whitespace/lib/whitespace.js:112:21)
    at /usr/share/atom/resources/app.asar/node_modules/whitespace/lib/whitespace.js:58:21
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at /usr/share/atom/resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.promptToSaveItem (/usr/share/atom/resources/app.asar/src/pane.js:690:23)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:636:18)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:17)
```

### Commands

```
     -8:02.8.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -6:23.8.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -6:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:19.4.0 settings-view:open (atom-text-editor.editor.power-mode)
 19x -5:51.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:55.4.0 markdown-preview-plus:sync-source (strong.)
     -4:08.3.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -4:02.1.0 window:run-package-specs (atom-text-editor.editor.power-mode.is-focused)
     -3:51.6.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
  4x -3:39.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:43.5.0 markdown-toc:toggle (atom-text-editor.editor.power-mode.is-focused)
     -2:01.9.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -1:30.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  6x -1:28.7.0 core:undo (atom-text-editor.editor.power-mode.is-focused)
     -0:23.6.0 term:open-split-down (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-gfm",
      "terminal-panel",
      "markdown-preview-opener"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atomic-chrome, v0.3.0
language-markdown, v0.13.0
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.4.0
markdown-preview-plus-opener, v0.2.0
markdown-scroll-sync, v2.1.2
markdown-toc, v0.4.1
minimap, v4.23.5
term, v0.2.4

# Dev
No dev packages
```

**Comment by lexcast** [comment] 2016-05-20 14:36
how can be this error reproduced?

**Comment by radlantern** [comment] 2016-06-09 17:13
I see this error when I attempt a project-wide replace where at least one file that will be modified is still open in the panel.  Closing the tab for the file that will be modified gets me past the error.

I think it may be occurring because it is attempting to spawn particles for a tab that is not active.

Note that when I spit the tab that will be edited to another panel, so it remains visible during the replace action, it still gives the error.

```
TypeError: Cannot read property 'screenPositionForBufferPosition' of undefined
    at Object.module.exports.ActivatePowerMode.spawnParticles (activate-power-mode.coffee:99)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\rcl\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.de…:182)
    at Object.module.exports.ActivatePowerMode.onChange (activate-power-mode.coffee:75)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25)
    at Emitter.module.exports.Emitter.emit (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:692)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:602)
    at SearchCallbackArgument.replace (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:75)
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:3
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:972
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:911
    at TextBuffer.module.exports.TextBuffer.scanInRange (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:949)
    at TextBuffer.module.exports.TextBuffer.scan (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:907)
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:969
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:828)
    at TextBuffer.module.exports.TextBuffer.replace (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buff…:967)
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:1073
    at Workspace.module.exports.Workspace.replace (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:1032)
    at ResultsModel.module.exports.ResultsModel.replace (C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\find-and-replace\lib\proj…:215)
    at C:\Users\rcl\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\find-and-replace\lib\proj…:529
```

**Comment by lexcast** [comment] 2016-08-04 15:51
this bug is still happening?

**Comment by radlantern** [comment] 2016-08-04 23:17
Looks like it is fixed.  Atom 1.9.3 and activate-power-mode 0.7.2

**Comment by lexcast** [comment] 2016-08-04 23:19
Great, thanks

**Closed by lexcast** 2016-08-04 23:19 UTC
Labels: bug

**Comment by local-minimum** [comment] 2017-10-25 07:20
This issue happened with a project wide replace to me right now using activate-power-mode 2.6.0 and Atom 1.20.1

**Comment by Wandang** [comment] 2018-02-15 12:16
Same for active-power-mode 2.7.0 and atom 1.23.3 on ubuntu 16.04 64bit

**Comment by 777ki** [comment] 2018-04-15 14:21
when i start vim mode,that error was occured,how can i fix it, yes that so coooooooooool that i can't drop it
