### ISSUE TITLE
Failed to load the activate-power-mode package

### ISSUE THREAD

**Issue by huanzhang** [JoelBesada/activate-power-mode#56] opened 2015-12-02 15:56 UTC
1. active power mode with Active Power Mode: Toggle
2. input some code in the Power Mode and close the file
3. open another file and reload atom window with : Window: Reload
4. the following error appears

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the activate-power-mode package

```
At Syntax error on line 2, column 2: One top level value expected

SyntaxError: Syntax error on line 2, column 2: One top level value expected
    at nodeTransforms.Block (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:74:15)
    at transformNode (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:197:12)
    at Object.parse (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/node_modules/cson-parser/lib/parse.js:203:12)
    at parseObject (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
    at parseContentsSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
    at Object.module.exports.readFileSync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:381:43
    at Array.map (native)
    at Package.module.exports.Package.loadMenus (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:379:42)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:111:19
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:386:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:667:21)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".bundle",
      ".git",
      "repositories",
      "vendor"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "hideGitIgnoredFiles": false,
    "disabledPackages": [
      "background-tips",
      "exception-reporting",
      "metrics"
    ],
    "projectHome": "/Users/zhanghuan/Code"
  },
  "editor": {
    "fontFamily": "Menlo",
    "invisibles": {},
    "fontSize": 15,
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "backUpBeforeSaving": true,
    "showIndentGuide": true,
    "preferredLineLength": 150
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
linter, v1.11.3
linter-rubocop, v0.4.4
pdf-view, v0.37.0
pig, v1.0.0
seti-syntax, v0.4.1
tablr, v0.9.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by lexcast** [comment] 2016-05-06 20:28
this is still happening with newest version?

**Comment by josealgardataborges** [comment] 2016-05-20 08:50
Yes... 

Cannot find module 'lodash.throttle'
Hide Stack Trace
Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/jose.borges/.atom/packages/activate-power-mode-0.5.2/lib/activate-power-mode.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/jose.borges/.atom/packages/activate-power-mode-0.5.2/lib/activate-power-mode.coffee:1:1)
    at Module._compile (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\jose.borges\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:743:28
![atompower](https://cloud.githubusercontent.com/assets/8929655/15422374/36ab645c-1e70-11e6-8644-e081bb90c97a.png)

**Comment by lexcast** [comment] 2016-05-20 14:34
@josealgardataborges how did you install the package?

**Comment by dyphoenix** [comment] 2016-06-07 16:39
the same as above...
windows10 
atom1.8.0
---------------------------
Failed to load the activate-power-mode package
Cannot find module 'lodash.throttle'
Hide Stack Trace
Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/samsungpc/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/samsungpc/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:1)
    at Module._compile (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\samsungpc\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:743:28
The error was thrown from the activate-power-mode package.

**Comment by dyphoenix** [comment] 2016-06-07 16:40
installed by the package download from https://github.com/JoelBesada/activate-power-mode.git

**Comment by lexcast** [comment] 2016-06-07 17:03
@dyphoenix why not installing by the atom package manager?

**Comment by dyphoenix** [comment] 2016-06-07 17:43
yep, i've get it down, like it very much, tks~

**Comment by luffy9412** [comment] 2016-07-11 10:26
@lexcast I encountered the same problem with @dyphoenix,I  already try to use atom package manager install but install error.Then I try to install by console command but install error too;

**Comment by lexcast** [comment] 2016-08-05 00:00
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.

**Comment by lexcast** [comment] 2016-08-05 00:01
Hi @luffy9412 what says the error?

**Closed by lexcast** 2016-08-05 00:00 UTC

**Comment by snowluliang** [comment] 2016-08-09 14:53
please help me!

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.6
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.7.3


### Stack Trace

Failed to load the activate-power-mode package

```
At Cannot find module 'lodash.throttle'

Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Snow/.atom/packages/activate-power-mode-master/lib/power-editor.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/Snow/.atom/packages/activate-power-mode-master/lib/power-editor.coffee:1:1)
    at Module._compile (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Snow/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:3:15)
    at Object.<anonymous> (file:///C:/Users/Snow/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:1)
    at Module._compile (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package.js:715:27)
    at C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Snow\AppData\Local\atom\app-1.9.6\resources\app.asar\src\atom-environment.js:749:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.3 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by lexcast** [comment] 2016-08-09 15:05
@snowluliang how did you install the package?

**Comment by liuchangxing** [comment] 2016-09-21 09:14
Hello, I am from China, I downloaded your compressed package, installed on the useless, why, the situation is similar to the above, I am a Windows7 system.

**Comment by liuchangxing** [comment] 2016-09-21 09:18
Is there a version of it, give me a link to download, I think it will be useful.

**Comment by liuchangxing** [comment] 2016-09-21 09:22
All right. I tried a version of the next version, and no use, how to do

**Comment by liuchangxing** [comment] 2016-09-21 09:27
![qq 20160921172704](https://cloud.githubusercontent.com/assets/22342099/18705382/a9197936-8020-11e6-9068-ca308e12c0f6.png)

**Comment by liuchangxing** [comment] 2016-09-21 10:16
Also, atom support for what font ah.

**Comment by lexcast** [comment] 2016-09-21 14:11
@liuchangxing try using the terminal running `apm install activate-power-mode` and show me the output.

**Comment by liuchangxing** [comment] 2016-09-22 02:08
Cannot find module 'lodash.throttle'
Hide Stack Trace
Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (D:\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (D:\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/activate-power-mode-changelog-update/lib/power-editor.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/activate-power-mode-changelog-update/lib/power-editor.coffee:1:1)
    at Module._compile (D:\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (D:\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/activate-power-mode-0.7.3/lib/activate-power-mode.coffee:3:15)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/activate-power-mode-0.7.3/lib/activate-power-mode.coffee:1:1)
    at Module._compile (D:\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (D:\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (D:\Atom\resources\app.asar\src\package.js:718:27)
    at D:\Atom\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (D:\Atom\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (D:\Atom\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (D:\Atom\resources\app.asar\src\package-manager.js:457:14)
    at D:\Atom\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (D:\Atom\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (D:\Atom\resources\app.asar\src\package-manager.js:397:19)
    at D:\Atom\resources\app.asar\src\atom-environment.js:754:28

**Comment by liuchangxing** [comment] 2016-09-22 02:09
Is this one?

**Comment by lexcast** [comment] 2016-09-22 02:14
mm no, but that problem is fixed by running
```
cd ~/.atom/packages/activate-power-mode
npm install
```

**Comment by liuchangxing** [comment] 2016-09-22 02:20
But，apm,can't be in my "Windos PowerShell"function

**Comment by liuchangxing** [comment] 2016-09-22 02:23
![qq 20160922102309](https://cloud.githubusercontent.com/assets/22342099/18735192/9643dd0e-80ae-11e6-8ae5-8b9fec07f968.png)

**Comment by liuchangxing** [comment] 2016-09-22 02:24
找不到路径  （path not found）

**Comment by liuchangxing** [comment] 2016-09-22 02:28
![image](https://cloud.githubusercontent.com/assets/22342099/18735268/2d8f96b2-80af-11e6-9fe1-db4d785e0fb6.png)
What's next?Oh! I'm so stupid.

**Comment by lexcast** [comment] 2016-09-22 03:21
Don't worry
from where you are in the terminal run:
``` 
cd activate-power-mode
npm install
```

**Comment by liuchangxing** [comment] 2016-09-22 04:17
![qq 20160922121252](https://cloud.githubusercontent.com/assets/22342099/18736890/243f0c1e-80be-11e6-87ad-65fa8102c291.png)
And what?This seems to be right.

**Comment by liuchangxing** [comment] 2016-09-22 04:24
No no no, it can't be used.

**Comment by liuchangxing** [comment] 2016-09-22 04:32
![qq 20160922123124](https://cloud.githubusercontent.com/assets/22342099/18737130/81775a88-80c0-11e6-9c1e-a2bcb4bc565c.png)
Sorry. I just put the folder name wrong.

**Comment by liuchangxing** [comment] 2016-09-22 11:01
![1gif](https://cloud.githubusercontent.com/assets/22342099/18745865/a4da4bf8-80f6-11e6-8803-9f5b818fbf8c.gif)
thank you very much!
It has been good.Really thank you so much!

**Comment by liuchangxing** [comment] 2016-09-22 11:08
![qq 20160922190735](https://cloud.githubusercontent.com/assets/22342099/18746088/fbfe9df2-80f7-11e6-98d8-0e63a8dc2785.png)
Oh! This feature I love it!

**Comment by lexcast** [comment] 2016-09-22 14:04
@liuchangxing great :tada:

**Comment by liuchangxing** [comment] 2016-09-22 14:26
thank you for your help.

**Comment by zhpass** [comment] 2016-09-23 09:01
![image](https://cloud.githubusercontent.com/assets/18256154/18780281/54ff7e82-81af-11e6-8e09-c1c1a85ff278.png)

**Comment by zhpass** [comment] 2016-09-23 09:05
![image](https://cloud.githubusercontent.com/assets/18256154/18780392/ea075144-81af-11e6-8af6-1a50fd842734.png)
why？？

**Comment by zhpass** [comment] 2016-09-23 10:02
![image](https://cloud.githubusercontent.com/assets/18256154/18782167/a6fe0aa2-81b7-11e6-9a20-4e4923a2dfb3.png)
why

**Comment by lexcast** [comment] 2016-09-23 14:40
@zhpass try installing with `apm install activate-power-mode`

**Comment by zhpass** [comment] 2016-09-24 08:10
its ok   thank you;

**Comment by JetCrusherTorpedo** [comment] 2016-10-30 21:18
+1 after update to 1.1.0

**Comment by lexcast** [comment] 2016-10-30 21:27
@JetCrusherTorpedo if the issue was just after the upgrade, try reopening atom.

**Comment by JetCrusherTorpedo** [comment] 2016-10-30 21:33
@lexcast Still occurs, tried relaunching twice. Here's the Stack Trace:
![image](https://cloud.githubusercontent.com/assets/8607522/19840161/e34df202-9ec6-11e6-9edf-07d2209e7a4a.png)

**Comment by lexcast** [comment] 2016-10-30 21:42
@JetCrusherTorpedo this doesn't seem related to this issue, can you open a new one? and please copy/paste the stack trace as text, would be more useful.

**Comment by JetCrusherTorpedo** [comment] 2016-10-30 21:45
@lexcast Atom says the error has already been reported and links to this issue

**Comment by lexcast** [comment] 2016-10-30 21:47
@JetCrusherTorpedo I know, but if you read this issue you will see is total different, I don't know how atom match existing issues but it fails sometimes.

**Comment by JetCrusherTorpedo** [comment] 2016-10-30 21:49
@lexcast alright, thanks

**Comment by acoret** [comment] 2016-12-10 10:34
sorry to bother,it installed error in my computer.Ubuntu 16.04
Atom is newly installed without other plugins(In fact other plugins fail to install)
I try first apm install activate-power-mode it is stucked with 
'Installing activate-power-mode to /home/uncrepter/.atom/packages'
so i try other way, git clone --depth=1 https://github.com/JoelBesada/activate-power-mode.git 
and cd ~/.atom/pack*/ac*,apm install,it failed(stucked).
then npm install,It just fail to isntall.
loadDep:lodash.throttle → ▀ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
that's what i got in screen.

**Comment by lexcast** [comment] 2016-12-10 16:41
@acoret if you try to install from the atom UI on Settings > Install?

**Comment by acoret** [comment] 2016-12-11 04:29
@lexcast amzing,it work now.

**Comment by YangFuLong** [comment] 2017-03-30 09:55
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 1.4.0


### Stack Trace

Failed to load the activate-power-mode package

```
At Cannot find module 'lodash.throttle'

Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/activate-power-mode/lib/power-editor.coffee:1:12)
    at /packages/activate-power-mode/lib/power-editor.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:4:15)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-chs-menu 1.0.0 
```
